### ISSUE TITLE
Data Collection for Fine-Tuning

### ISSUE THREAD

**Issue by aminpdik** [niejiahao1998/IFA#13]
Hello 

Thanks for the great paper.

During the fine-tuning phase, how many images did you utilize from the target domain? Did you use just one image per novel class?

Could you please explain this in detail?

Best

**Comment by niejiahao1998** [comment]
Hello.
Yes, we use 1 image per class during fine-tuning (under 1-shot setting).

**Comment by aminpdik** [comment]
Thanks for your quick response @niejiahao1998 

For instance, for the fine-tuning of the DeepGlobe dataset, you randomly select 7 images (one image from each of the 7 categories) for the one-shot setting and 35 images (five images per category) for the five-shot setting. Is it right?

**Comment by niejiahao1998** [comment]
Yes, you are correct. However, there are only 6 categories in the Deepglobe. Thus, we randomly select 6 images for 1-shot setting, and 30 images for 5-shot.

**Comment by zhutianlee** [comment]
the fituning data is sampled from test data?
